- id: automation01
  alias: Start HomeKit
  trigger:
  - platform: homeassistant
    event: start
  action:
  - delay: 00:05
  - service: homekit.start
- id: automation02
  alias: Update Kodi
  trigger:
  - at: 01:19:00
    platform: time
  action:
  - service: script.update_library
